// Settings > Backup: one backup for the whole workspace, with the pages to
// include chosen by checkbox; automatic backups, retention, roles.

Tests.suite('backup', 'Settings > Backup', async ({ page, BASE, check, skip, section, same, artifact, sleep }) => {
  const errors = []
  page.on('pageerror', (e) => errors.push(`pageerror @ ${page.url()}: ${e.message}`))

  // Same-document hash changes don't reload; always load through a blank page.
  const goto = async (p) => { await page.goto('about:blank'); await page.goto(BASE + p, { waitUntil: 'domcontentloaded' }); await page.waitForTimeout(450) }
  const reset = async () => { await page.goto(BASE + 'login.html', { waitUntil: 'domcontentloaded' }); await page.evaluate(() => { Store.reset(); Store.login('admin', 'admin') }) }
  const backups = () => page.evaluate(() => Store.listBackups())
  const settingsOf = () => page.evaluate(() => Store.get().backupSettings)
  const toast = () => page.$eval('#toast-root', (e) => e.innerText.trim()).catch(() => '')
  const take = async () => { await page.click('#bk-take'); await page.waitForTimeout(250) }
  const items = () => page.$$eval('.bk-item', (lis) => lis.map((li) => ({ meta: li.querySelector('.bk-item-meta').textContent.trim(), chips: [...li.querySelectorAll('.bk-chip')].map((c) => c.textContent.trim()), id: li.querySelector('[data-bk-download]').getAttribute('data-bk-download') })))
  const counter = () => page.textContent('#bk-selected-count')
  const switchOn = async (sel) => (await page.getAttribute(sel, 'aria-checked')) === 'true'
  const status = () => page.textContent('.bk-status').then((t) => t.replace(/\s+/g, ' ').trim())
  const ageBackups = () => page.evaluate(() => { const l = Store.listBackups(); l.forEach((b) => { b.createdDate = '2020-01-01 00:00:00' }); localStorage.setItem('univa-html-backups-v1', JSON.stringify(l)) })

  // ============================================================ sidebar + page
  section('Sidebar entry and the page')
  await reset()
  await goto('settings.html')
  const sectionLabels = await page.$$eval('.sidebar-section-label', (els) => els.map((e) => e.textContent.trim()))
  check('sidebar has a Settings section', sectionLabels.includes('Settings'), sectionLabels)
  const link = await page.$eval('a.sidebar-child-link[href="settings.html"]', (a) => ({ text: a.textContent.trim(), active: a.classList.contains('active') }))
  check('with a Backup link to settings.html, highlighted on the page', link.text === 'Backup' && link.active, link)
  check('page title is Settings', (await page.textContent('.page-title')) === 'Settings')
  check('breadcrumb is Home / Settings / Backup', same(await page.$$eval('.top-bar-breadcrumbs a, .top-bar-breadcrumbs span.breadcrumb-current', (e) => e.map((x) => x.textContent.trim())), ['Home', 'Settings', 'Backup']))
  for (const url of ['application-detail.html#app0', 'application-detail.html#app_ems', 'notion.html#app_notion', 'notion.html#app1']) {
    await goto(url)
    check(`no backup button on ${url}`, (await page.locator('#app-backup-btn').count()) === 0 && (await page.locator('button:has-text("Backup")').count()) === 0)
  }

  // ============================================================ picker
  section('Pages to back up')
  await goto('settings.html')
  const groups = await page.$$eval('.bk-group-head span:first-of-type', (e) => e.map((x) => x.textContent.trim()))
  check('groups follow the sidebar', same(groups, ['Dashboard', 'Applications', 'Devices management', 'Assets management', 'Shift management', 'Rule engines', 'Users & permissions']), groups)
  const appPages = await page.$$eval('[data-bk-in="applications"] ~ .bk-page-name', (e) => e.map((x) => x.textContent.trim()))
  check('Applications lists All applications and every application', same(appPages, ['All applications', 'PMS', 'EMS', 'Custom App', 'CMS', 'Fleet Tracker']), appPages)
  check('Credentials, Software OTA and Data explorer are not offered', (await page.locator('[data-bk-page="credentials"], [data-bk-page="softwareOta"], [data-bk-page="deviceData"]').count()) === 0)
  check('everything is ticked by default', (await counter()) === '20 of 20 selected' && (await page.locator('[data-bk-page]:not(:checked)').count()) === 0)
  check('empty state before the first backup', /No backups yet/.test(await page.textContent('.bk-body')) && (await page.textContent('#bk-stat-last')) === 'Never')
  check('each page shows how much it holds', /13 devices/.test(await page.textContent('[data-bk-page="devices"] ~ .bk-page-count')) && /5 applications/.test(await page.textContent('[data-bk-page="applications"] ~ .bk-page-count')), await page.textContent('[data-bk-page="devices"] ~ .bk-page-count'))

  // ============================================================ take / list / download / delete
  section('Take, list, download, delete')
  const counts = await page.evaluate(() => { const s = Store.get(); return { devices: s.devices.length, apps: s.applications.length, users: s.users.length, meters: s.emsMeters.length, machines: s.cmsMachines.length, notion: s.notionPages.length } })
  await take()
  let list = await backups()
  check('Take backup now stores one workspace backup', list.length === 1 && !list[0].appId, list.length)
  check('it covers all 20 pages', list[0].pages.length === 20 && same(Object.keys(list[0].data).sort(), list[0].pages.map((p) => p.key).sort()), list[0].pages.length)
  check('devices page holds the devices', list[0].data.devices.length === counts.devices)
  check('All applications holds the application list', list[0].data.applications.length === counts.apps)
  check('EMS keeps its own collections', list[0].data['app:app_ems'].emsMeters.length === counts.meters && !!list[0].data['app:app_ems'].emsTodReadings)
  check('CMS keeps its machines', list[0].data['app:app_cms'].cmsMachines.length === counts.machines)
  check('Custom App holds its pages', list[0].data['app:app_notion'].notionPages.length === 3)
  check('an application with nothing saved is empty, not leaking others', !list[0].data['app:app1'].notionPages && !list[0].data['app:app1'].applicationRecords)
  check('PMS holds its manual records', (list[0].data['app:app0'].applicationRecords || []).length > 0)
  check('users page holds the users', list[0].data.users.length === counts.users)
  check('recorded as manual, by admin, with a size', list[0].trigger === 'manual' && list[0].createdBy === 'admin' && list[0].sizeBytes > 1000)
  check('toast confirms the backup', /Backup taken \(20 pages/.test(await toast()), await toast())
  let rows = await items()
  check('history row says pages and size', /20 pages/.test(rows[0].meta) && /(KB|MB)$/.test(rows[0].meta), rows[0].meta)
  check('row shows page chips with a "more" chip', rows[0].chips.includes('Dashboard') && rows[0].chips.some((c) => /^\+14 more$/.test(c)), rows[0].chips)
  check('stats updated', (await page.textContent('#bk-stat-count')) === '1' && (await page.textContent('#bk-stat-last')) === 'just now')

  await page.waitForTimeout(1100)
  await take()
  list = await backups()
  rows = await items()
  check('second backup listed first (newest first)', rows.length === 2 && rows[0].id === list[1].id && rows[1].id === list[0].id)

  const [dl] = await Promise.all([page.waitForEvent('download'), page.click(`[data-bk-download="${list[1].id}"]`)])
  const sql = await dl.text()
  check('Download gives an .sql file named for the time', /^univa-backup-\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}\.sql$/.test(dl.suggestedFilename()), dl.suggestedFilename())
  check('the button says Download SQL', /Download SQL/.test(await page.textContent(`[data-bk-download="${list[1].id}"]`)))
  check('the file is a PostgreSQL script in a transaction', sql.startsWith('-- Univa database backup') && sql.includes('\nBEGIN;\n') && sql.trimEnd().endsWith('COMMIT;') && /-- Pages \(20\): Dashboard/.test(sql))
  const deviceInsert = sql.slice(sql.indexOf('INSERT INTO "devices"'))
  const deviceRows = deviceInsert.slice(0, deviceInsert.indexOf(';\n')).split('\n').filter((l) => /^  \(/.test(l)).length
  check('a table per collection, a row per record', /CREATE TABLE "devices" \(/.test(sql) && deviceRows === counts.devices && /CREATE TABLE "ems_meters"/.test(sql) && /CREATE TABLE "notion_pages"/.test(sql), { deviceRows })

  await page.click(`[data-bk-delete="${list[0].id}"]`)
  check('delete asks for confirmation', await page.locator('#confirm-dialog-confirm').isVisible())
  await page.click('#confirm-dialog-confirm')
  await page.waitForTimeout(250)
  check('Delete removes just that backup', same((await backups()).map((b) => b.id), [list[1].id]) && (await items()).length === 1)
  check('delete toast', /Backup deleted successfully/.test(await toast()), await toast())

  // ============================================================ choosing pages
  section('Choosing which pages go in')
  await page.click('[data-bk-page="devices"]')
  check('unticking a page updates the counter', (await counter()) === '19 of 20 selected', await counter())
  check('its group shows 1/2 and is partly ticked', (await page.textContent('[data-bk-group-count="devices"]')) === '1/2' && (await page.$eval('[data-bk-group="devices"]', (e) => e.indeterminate)))
  check('the choice is saved', same((await settingsOf()).excluded, ['devices']), await settingsOf())
  await take()
  list = await backups()
  let latest = list[list.length - 1]
  check('the backup leaves that page out', latest.pages.length === 19 && !latest.data.devices && !latest.pages.some((p) => p.key === 'devices') && !!latest.data.deviceProfiles)
  await goto('settings.html')
  check('the choice survives a reload', !(await page.isChecked('[data-bk-page="devices"]')) && (await counter()) === '19 of 20 selected')
  await page.click('[data-bk-group="users"]')
  check('a group box unticks all its pages', (await counter()) === '16 of 20 selected' && same((await settingsOf()).excluded.sort(), ['devices', 'roles', 'userGroups', 'users']), await settingsOf())
  await page.click('[data-bk-group="users"]')
  check('and ticks them again', (await counter()) === '19 of 20 selected')
  await page.click('[data-bk-page="app:app_ems"]')
  await take()
  latest = (await backups()).pop()
  check('leaving one application out drops its data but keeps the application list', !latest.data['app:app_ems'] && latest.data.applications.some((a) => a.id === 'app_ems') && !!latest.data['app:app_cms'])
  await page.click('#bk-clear')
  check('Clear unticks everything and disables Take backup', (await counter()) === '0 of 20 selected' && (await page.locator('#bk-take').isDisabled()))
  const before = (await backups()).length
  await page.click('#bk-take', { force: true, timeout: 1500 }).catch(() => {})
  check('nothing is taken with nothing chosen', (await backups()).length === before)
  await page.click('#bk-select-all')
  check('Select all brings everything back', (await counter()) === '20 of 20 selected' && !(await page.locator('#bk-take').isDisabled()) && same((await settingsOf()).excluded, []))

  // dashboard layouts and other saved pieces
  await page.evaluate(() => {
    localStorage.setItem('univa_dashboard_layout_v1', JSON.stringify([{ id: 'w1' }, { id: 'w2' }]))
    localStorage.setItem('univa_dashboard_layout_v1__app-app1', JSON.stringify([{ id: 'w9' }]))
    localStorage.setItem('univa_dashboard_layout_v1__ems-meter-meter1', JSON.stringify([{ id: 'w5' }]))
  })
  await goto('settings.html')
  check('the Dashboard page counts its widgets', /2 widgets/.test(await page.textContent('[data-bk-page="dashboard"] ~ .bk-page-count')), await page.textContent('[data-bk-page="dashboard"] ~ .bk-page-count'))
  await take()
  latest = (await backups()).pop()
  check('the dashboard layout is in the backup', latest.data.dashboard.widgets.length === 2)
  check('an application dashboard layout goes with that application', same(Object.keys(latest.data['app:app1'].dashboardLayouts), ['app-app1']))
  check('EMS meter layouts go with EMS', same(Object.keys(latest.data['app:app_ems'].dashboardLayouts), ['ems-meter-meter1']))
  // these fake widgets would crash the real Dashboard page
  await page.evaluate(() => ['univa_dashboard_layout_v1', 'univa_dashboard_layout_v1__app-app1', 'univa_dashboard_layout_v1__ems-meter-meter1'].forEach((k) => localStorage.removeItem(k)))

  // ============================================================ lifecycle
  section('Lifecycle')
  const scratchId = await page.evaluate(() => Store.addApplication({ name: 'Scratch app' }).id)
  await goto('settings.html')
  await take()
  await page.evaluate((id) => Store.removeApplication(id), scratchId)
  latest = (await backups()).pop()
  check('a backup keeps an application deleted afterwards', latest.data.applications.some((a) => a.id === scratchId) && !!latest.data['app:' + scratchId])
  await page.evaluate(() => { const raw = JSON.parse(localStorage.getItem('univa-html-demo-v26')); raw.applicationBackups = [{ id: 'old', appId: 'app0' }]; raw.applicationBackupSettings = { app0: { auto: true } }; localStorage.setItem('univa-html-demo-v26', JSON.stringify(raw)) })
  await goto('settings.html')
  check('per-application backups from before are dropped', await page.evaluate(() => !('applicationBackups' in Store.get()) && !('applicationBackupSettings' in Store.get())))
  const keep = (await backups()).length
  await page.evaluate(() => { const raw = JSON.parse(localStorage.getItem('univa-html-demo-v26')); raw.name = 'bump'; localStorage.setItem('univa-html-demo-v26', JSON.stringify(raw)) })
  check('backups are kept apart from the data blob', keep > 0 && !(await page.evaluate(() => localStorage.getItem('univa-html-demo-v26').includes('"pages":[{"key"'))))
  await reset()
  check('resetting the demo data clears backups', (await backups()).length === 0)

  // ============================================================ storage full
  section('Browser storage full')
  await goto('settings.html')
  await page.evaluate(() => { window.__origSet = Storage.prototype.setItem; Storage.prototype.setItem = function () { throw new DOMException('quota', 'QuotaExceededError') } })
  await page.click('#bk-take')
  await page.waitForTimeout(250)
  await page.evaluate(() => { Storage.prototype.setItem = window.__origSet })
  check('a full browser is reported, not crashed', /not enough browser storage/i.test(await toast()), await toast())
  check('nothing half-saved and the page still works', (await backups()).length === 0 && (await page.locator('#bk-take').isVisible()))

  // ============================================================ settings tab
  section('Settings tab: automatic backups, retention')
  await reset()
  await goto('settings.html')
  check('opens on the Backups tab', (await page.getAttribute('[data-bk-tab="backups"]', 'aria-selected')) === 'true')
  check('status chip says automatic backups are off', /Automatic backups off/.test(await status()), await status())
  await page.click('[data-bk-tab="settings"]')
  check('Settings tab has Automatic backups and Retention', (await page.locator('.bk-section').count()) === 2)
  check('defaults: auto off, keep 10', !(await switchOn('#bk-auto')) && (await page.inputValue('#bk-keep')) === '10')
  check('frequency is disabled while off', await page.locator('input[name="bk-frequency"]').first().isDisabled())
  check('page summary counts the chosen pages', /20 of 20 pages/.test(await page.textContent('#bk-pages-summary')), await page.textContent('#bk-pages-summary'))
  await page.click('#bk-auto')
  await page.waitForTimeout(300)
  let l2 = await backups()
  check('switch on is saved', (await settingsOf()).auto === true)
  check('turning it on takes the first backup straight away', l2.length === 1 && l2[0].trigger === 'auto', l2.map((x) => x.trigger))
  check('toast announces the automatic backup', /Automatic backup taken \(20 pages/.test(await toast()), await toast())
  check('status chip shows the schedule', /Automatic · Daily/.test(await status()), await status())
  check('next backup time is shown', /Next backup/.test(await page.textContent('#bk-next')), await page.textContent('#bk-next'))
  check('stayed on the Settings tab', (await page.getAttribute('[data-bk-tab="settings"]', 'aria-selected')) === 'true')
  await page.click('input[name="bk-frequency"][value="weekly"]')
  await page.waitForTimeout(250)
  check('weekly is saved and the next backup is a week out', (await settingsOf()).frequency === 'weekly' && /Next backup \d{2} \w{3} at \d{2}:\d{2}/.test(await page.textContent('#bk-next')), await page.textContent('#bk-next'))
  check('settings toast', /Backup settings saved successfully/.test(await toast()), await toast())
  await page.click('#bk-choose-pages')
  await page.waitForTimeout(300)
  check('Choose pages goes to the picker on the Backups tab', (await page.getAttribute('[data-bk-tab="backups"]', 'aria-selected')) === 'true' && (await page.locator('#bk-picker').isVisible()))
  check('the history lists the automatic one with an Automatic badge', /Automatic/.test(await page.textContent('.bk-item .bk-badge')))

  // retention: lowering the limit deletes nothing until the next backup
  await take(); await page.waitForTimeout(150); await take(); await page.waitForTimeout(150); await take()
  check('four backups so far', (await backups()).length === 4)
  await page.click('[data-bk-tab="settings"]')
  await page.selectOption('#bk-keep', '3')
  await page.waitForTimeout(250)
  check('retention is saved, nothing deleted yet', (await settingsOf()).keep === 3 && (await backups()).length === 4)
  await take()
  l2 = await backups()
  check('the next backup keeps only the latest 3', l2.length === 3 && l2.every((x) => x.trigger === 'manual'), l2.map((x) => x.trigger))
  check('toast says older backups were deleted', /2 oldest backups were deleted to keep the latest 3/.test(await toast()), await toast())
  await page.selectOption('#bk-keep', '0')
  await page.waitForTimeout(250)
  await take(); await take()
  check('Keep all stops pruning', (await settingsOf()).keep === 0 && (await backups()).length === 5)
  await page.selectOption('#bk-keep', '3')
  await page.waitForTimeout(250)

  // automatic backups on any page
  section('Automatic backups run on any page')
  await ageBackups()
  const n0 = (await backups()).length
  await goto('devices.html')
  await page.waitForFunction(() => window.Backup).catch(() => {})
  await page.waitForTimeout(400)
  l2 = await backups()
  const newest = l2[l2.length - 1]
  check('an overdue backup is taken when any page opens', newest.trigger === 'auto' && newest.createdDate > '2026-01-01', { n0, now: l2.length, trigger: newest.trigger })
  check('and the retention limit is applied', l2.length === 3, l2.length)
  check('with a toast', /Automatic backup taken/.test(await toast()), await toast())
  const idAfter = newest.id
  await goto('dashboard.html')
  await page.waitForTimeout(300)
  l2 = await backups()
  check('opening another page straight away does not take another', l2[l2.length - 1].id === idAfter)
  await ageBackups()
  await goto('settings.html')
  l2 = await backups()
  check('opening the Settings page takes it too when due', l2[l2.length - 1].trigger === 'auto' && l2[l2.length - 1].createdDate > '2026-01-01')
  await page.click('[data-bk-tab="settings"]')
  await page.click('#bk-auto')
  await page.waitForTimeout(250)
  check('turning it off stops automatic backups', !(await switchOn('#bk-auto')) && /Automatic backups off/.test(await status()))
  await ageBackups()
  await goto('devices.html')
  await page.waitForTimeout(400)
  check('with it off, an overdue workspace is left alone', (await backups()).every((x) => x.createdDate === '2020-01-01 00:00:00'))
  await goto('settings.html')
  await page.click('[data-bk-tab="settings"]')
  await page.click('#bk-auto')
  await page.waitForTimeout(250)
  await ageBackups()
  // untick every page, then let an overdue automatic backup try
  await page.click('[data-bk-tab="backups"]')
  await page.click('#bk-clear')
  await ageBackups()
  const n1 = (await backups()).length
  await goto('devices.html')
  await page.waitForTimeout(400)
  check('automatic backup does nothing when no page is chosen', (await backups()).length === n1)
  await goto('settings.html')
  check('the page shows the cleared choice', (await counter()) === '0 of 20 selected')
  await page.click('#bk-select-all')

  // ============================================================ roles
  section('Roles: who can use Settings > Backup')
  await reset()
  await page.evaluate(() => {
    Store.addTenantUser('t1', { name: 'Mia Member', email: 'mia.member@northbridge.com', role: 'Member' })
    Store.addTenantUser('t1', { name: 'Vic Viewer', email: 'vic.viewer@northbridge.com', role: 'Viewer' })
    Store.setBackupSettings({ auto: true, frequency: 'daily', keep: 10, excluded: [] })
  })
  const loginAs = async (email) => { await page.evaluate(({ email }) => { Store.logout(); return Store.login(email, '12345', 'NORTHBRIDGE') }, { email }) }
  const hasLink = () => page.locator('a.sidebar-child-link[href="settings.html"]').count()
  await loginAs('mia.member@northbridge.com')
  await goto('dashboard.html')
  check('a Member has no Settings link', (await hasLink()) === 0)
  await goto('settings.html')
  check('and a Member opening the page directly is turned away', (await page.textContent('#app-content')).includes('do not have permission'))
  check('a Member opening a page does not trigger the automatic backup', (await backups()).length === 0)
  await loginAs('vic.viewer@northbridge.com')
  await goto('settings.html')
  check('a Viewer is turned away too', (await hasLink()) === 0 && (await page.textContent('#app-content')).includes('do not have permission'))
  await loginAs('omar.salim@northbridge.com')
  await goto('settings.html')
  check('an Admin sees the link and the page', (await hasLink()) === 1 && (await page.locator('#bk-take').count()) === 1)
  check('and the automatic backup ran for them', (await backups()).length === 1 && (await backups())[0].trigger === 'auto')
  await loginAs('dana.whitfield@northbridge.com')
  await goto('settings.html')
  check('an Owner too', (await hasLink()) === 1 && (await page.locator('#bk-take').count()) === 1)
  check('the tenant\'s backup holds only the applications that tenant can see', await (async () => { await take(); const b = (await backups()).pop(); const visible = await page.evaluate(() => Store.get().applications.map((a) => a.id)); return same(b.data.applications.map((a) => a.id), visible) && b.data.users.length === (await page.evaluate(() => Store.get().users.length)) })())
  // no permission setting can open it up to another role, or close it to an Admin
  await loginAs('mia.member@northbridge.com')
  await page.evaluate(() => Store.setRolePermissions('Member', { settings: { view: true, create: true, edit: true, delete: true, fields: {} } }))
  await goto('dashboard.html')
  check('granting Settings to the Member role does nothing: still no link', (await hasLink()) === 0)
  await goto('settings.html')
  check('and the page is still closed to them', (await page.textContent('#app-content')).includes('do not have permission') && (await page.locator('#bk-take').count()) === 0)
  check('the Settings checks are role-only', await page.evaluate(() => !Store.hasPermission('settings', 'view') && !Store.hasPermission('settings', 'edit')))
  await loginAs('omar.salim@northbridge.com')
  await page.evaluate(() => Store.setRolePermissions('Admin', { settings: { view: false, create: false, edit: false, delete: false, fields: {} } }))
  await goto('settings.html')
  check('denying Settings to the Admin role does nothing either', (await hasLink()) === 1 && (await page.locator('#bk-take').count()) === 1)
  const roleChecks = {}
  for (const [role, email] of [['Owner', 'dana.whitfield@northbridge.com'], ['Admin', 'omar.salim@northbridge.com'], ['Member', 'mia.member@northbridge.com'], ['Viewer', 'vic.viewer@northbridge.com']]) {
    await loginAs(email)
    roleChecks[role] = await page.evaluate(() => Store.hasPermission('settings', 'view') && Store.hasPermission('settings', 'edit'))
  }
  check('Owner and Admin only: ' + JSON.stringify(roleChecks), same(roleChecks, { Owner: true, Admin: true, Member: false, Viewer: false }))
  check('the plain demo login (no tenant) is an owner', await (async () => { await reset(); return page.evaluate(() => Store.hasPermission('settings', 'view')) })())

  check('no JavaScript errors on any page', errors.length === 0, errors)
})
