// A device's own page (device-detail.html): the seven tabs and what can be done
// on each. The device is the demo's "Forklift Unit 3" (id d1), which starts with
// no token, one active alert and two delivered commands.

Tests.suite('device-detail', 'A device\'s page: overview, alerts, commands, relations, data', async ({ page, BASE, check, skip, section, same }) => {
  const errors = []
  page.on('pageerror', (e) => errors.push(`pageerror @ ${page.url()}: ${e.message}`))

  const open = async (url) => {
    await page.goto('about:blank')
    await page.goto(BASE + url)
    await page.waitForSelector('.device-detail-title, .device-not-found')
    await page.waitForTimeout(150)
  }
  const fresh = async () => {
    await page.goto(BASE + 'login.html')
    await page.evaluate(() => { Store.reset(); Store.login('admin', 'admin') })
    await open('device-detail.html#d1')
  }
  const device = () => page.evaluate(() => Store.get().devices.find((d) => d.id === 'd1'))
  const tab = async (key) => {
    await page.click(`[data-tab="${key}"]`)
    await page.waitForTimeout(120)
  }
  const toast = async () => {
    await page.waitForSelector('.device-toast-message')
    return page.textContent('.device-toast-message')
  }
  const markIn = (selector, text) => page.evaluate((arg) => {
    document.querySelectorAll('[data-test-row]').forEach((el) => el.removeAttribute('data-test-row'))
    const row = Array.from(document.querySelectorAll(arg.selector)).find((r) => r.textContent.includes(arg.text))
    if (row) row.setAttribute('data-test-row', '1')
    return Boolean(row)
  }, { selector, text })
  const rowMenu = async (selector, text, label) => {
    if (!(await markIn(selector, text))) throw new Error(`no ${selector} has "${text}" in it`)
    await page.click('[data-test-row] [data-menu-toggle]')
    await page.click(`[data-test-row] .row-menu-item:has-text("${label}")`)
  }
  const pill = (selector) => page.textContent(selector)

  // ----------------------------------------------------------------- header
  section('The header and the tabs')
  await fresh()
  check('the title names the device and its endpoint ID', (await page.textContent('.device-detail-title')).replace(/\s+/g, ' ').trim() === 'Forklift Unit 3 (ID: ep-88213)')
  const tabs = await page.$$eval('[data-tab]', (els) => els.map((el) => el.textContent.trim()))
  check('there are seven tabs', same(tabs, ['Overview', 'Alerts', 'Commands', 'Relations', 'Data publish', 'Data logs', 'Custom widgets']), tabs)
  check('Overview is the one showing', same(await page.$$eval('[data-tab].active', (els) => els.map((el) => el.textContent.trim())), ['Overview']))
  const crumbs = () => page.$$eval('.top-bar-breadcrumbs > *:not(.breadcrumb-separator)', (els) => els.map((el) => el.textContent.trim()))
  check('the breadcrumbs name the device and the tab', same(await crumbs(), ['Home', 'Devices', 'Device ep-88213', 'Overview']), await crumbs())
  await tab('alerts')
  check('moving to another tab moves the highlight and the last breadcrumb', same(await page.$$eval('[data-tab].active', (els) => els.map((el) => el.textContent.trim())), ['Alerts']) && (await crumbs())[3] === 'Alerts', await crumbs())
  check('the sidebar keeps Devices highlighted', same(await page.$$eval('.sidebar .active', (els) => els.map((el) => el.textContent.trim())), ['Devices']))
  await tab('overview')
  check('a device without a token shows a banner about activating it, which can be dismissed', (await page.locator('.token-info-banner').isVisible()) && (await (async () => { await page.click('#token-banner-close'); return !(await page.locator('.token-info-banner').isVisible()) })()))

  // --------------------------------------------------------------- overview
  section('Overview: metadata')
  const keysOf = () => page.$$eval('.metadata-list-row .metadata-key', (els) => els.map((el) => el.textContent.trim()))
  const initial = await keysOf()
  check('the metadata and the live readings are listed together: five stored fields, then speed and battery', same(initial, ['appName', 'appVersion.name', 'appVersion.registeredDate', 'createdDate', 'deviceId', 'speed', 'battery']), initial)
  check('a stored field shows its value', (await page.textContent('.metadata-list-row[data-field-id="d1-md1"] .metadata-value')).includes('Vehicles'))
  check('a reading shows its value and unit', /^\s*[\d.]+km\/h\s*$/.test(await markIn('.metadata-list-row', 'speed').then(() => page.textContent('[data-test-row] .metadata-value'))), await page.textContent('[data-test-row] .metadata-value'))

  await page.fill('#metadata-new-key', '   ')
  await page.click('#metadata-add-btn')
  check('adding a field with no key does nothing', (await keysOf()).length === 7)
  await page.fill('#metadata-new-key', 'zone')
  await page.fill('#metadata-new-value', 'north')
  await page.click('#metadata-add-btn')
  check('adding a field puts it in the list and the data, and says so', (await keysOf()).includes('zone') && (await device()).metadata.some((f) => f.key === 'zone' && f.value === 'north') && (await toast()) === 'Metadata field added')
  await rowMenu('.metadata-list-row', 'zone', 'Edit value')
  await page.waitForSelector('#metadata-edit-input')
  check('Edit value turns the value into a box holding it', (await page.inputValue('#metadata-edit-input')) === 'north')
  await page.fill('#metadata-edit-input', 'south')
  await page.click('[data-save-field]')
  check('Save changes it', (await device()).metadata.find((f) => f.key === 'zone').value === 'south' && (await toast()) === 'Updated "zone"')
  await rowMenu('.metadata-list-row', 'zone', 'Delete value')
  await page.waitForSelector('#confirm-dialog-confirm')
  check('Delete value asks first, naming the field', (await page.textContent('.confirm-dialog-message')).includes('zone'))
  await page.click('#confirm-dialog-confirm')
  check('and then removes it', !(await keysOf()).includes('zone') && !(await device()).metadata.some((f) => f.key === 'zone'))

  await page.click('#metadata-search-toggle')
  await page.fill('#metadata-search-input', 'APP')
  check('searching narrows the fields and readings by key, in any case', same(await keysOf(), ['appName', 'appVersion.name', 'appVersion.registeredDate']), await keysOf())
  await page.fill('#metadata-search-input', 'batt')
  check('and finds a reading', same(await keysOf(), ['battery']))
  await page.click('#metadata-search-toggle')

  section('Overview: token')
  check('the token starts as unavailable, with a Create button and no token shown', (await pill('#token-panel .status-pill')) === 'Unavailable' && (await page.locator('#token-panel [data-token-action="create"]').count()) === 1 && (await page.locator('.token-value').count()) === 0)
  await page.click('[data-token-action="create"]')
  const token1 = await page.textContent('.token-value')
  check('Create makes an active token and shows it', (await pill('#token-panel .status-pill')) === 'active' && token1.length >= 16 && (await device()).tokenStatus === 'active' && (await toast()) === 'Token created', token1)
  await page.click('[data-token-action="suspend"]')
  check('Suspend suspends it, and the buttons become Resume and Revoke', (await pill('#token-panel .status-pill')) === 'suspended' && same(await page.$$eval('[data-token-action]', (els) => els.map((el) => el.textContent.trim())), ['Resume', 'Revoke']))
  await page.click('[data-token-action="resume"]')
  check('Resume makes it active again, with the same token', (await pill('#token-panel .status-pill')) === 'active' && (await page.textContent('.token-value')) === token1)
  await page.click('[data-token-action="revoke"]')
  check('Revoke revokes it, and the only button left is Reissue', (await pill('#token-panel .status-pill')) === 'revoked' && same(await page.$$eval('[data-token-action]', (els) => els.map((el) => el.textContent.trim())), ['Reissue token']))
  await page.click('[data-token-action="reissue"]')
  check('Reissue gives a new token', (await pill('#token-panel .status-pill')) === 'active' && (await page.textContent('.token-value')) !== token1)

  section('Overview: telemetry')
  const ranges = await page.$$eval('#telemetry-range-select option', (els) => els.map((el) => el.value))
  check('the chart can show the last 5 minutes, 1 hour, 24 hours or 7 days', same(ranges, ['5m', '1h', '24h', '7d']) && (await page.inputValue('#telemetry-range-select')) === '1h', ranges)
  const linesFor = () => page.$$eval('#telemetry-svg path', (els) => els.length)
  check('the chart draws a line for each series', (await linesFor()) >= 2, await linesFor())
  const label1h = await page.$$eval('#telemetry-chart-wrap', (els) => els[0].textContent.replace(/\s+/g, ' ').trim())
  await page.selectOption('#telemetry-range-select', '7d')
  const label7d = await page.$$eval('#telemetry-chart-wrap', (els) => els[0].textContent.replace(/\s+/g, ' ').trim())
  check('choosing another range redraws it, with different time labels', label1h !== label7d && (await linesFor()) >= 2, { label1h, label7d })
  await page.click('#series-panel-toggle')
  const chips = await page.$$eval('[data-toggle-metric]', (els) => els.map((el) => el.textContent.trim()))
  check('the series list names each series', same(chips, ['Speed', 'Battery']), chips)
  const linesBefore = await linesFor()
  await page.click('[data-toggle-metric="battery"]')
  check('switching a series off removes its line', (await linesFor()) < linesBefore && (await page.textContent('#series-panel-toggle')).includes('1/2'), { linesBefore, now: await linesFor() })
  await page.click('#telemetry-refresh-btn')
  check('Refresh says it refreshed', (await toast()) === 'Telemetry refreshed')

  section('Panels can be maximised')
  await page.click('#metadata-panel [aria-label="Expand"]')
  check('Expand makes a panel fill the page, and its button then says Restore', (await page.evaluate(() => document.getElementById('metadata-panel').classList.contains('panel-maximized'))) && (await page.getAttribute('#metadata-panel [aria-label="Restore"]', 'title')) === 'Restore')
  await page.click('#metadata-panel [aria-label="Restore"]')
  check('Restore puts it back', !(await page.evaluate(() => document.getElementById('metadata-panel').classList.contains('panel-maximized'))))

  // ----------------------------------------------------------------- alerts
  section('Alerts')
  await fresh()
  await tab('alerts')
  const alertRow = () => page.$$eval('.data-table tbody tr', (rows) => rows.map((r) => r.textContent.replace(/\s+/g, ' ').trim()))
  const alerts = await alertRow()
  check('the device\'s one alert is listed with its type, severity, reason and state', alerts.length === 1 && alerts[0].includes('Threshold breach') && alerts[0].includes('warning') && alerts[0].includes('Value reached 68.4 (threshold 64.0)') && alerts[0].includes('active'), alerts)
  const menuItems = () => page.$$eval('.data-table tbody tr .row-menu-item', (els) => els.map((el) => el.textContent.trim()))
  check('an active alert can be acknowledged or resolved', same(await menuItems(), ['Acknowledge', 'Resolve']))
  await rowMenu('.data-table tbody tr', 'Threshold breach', 'Acknowledge')
  check('Acknowledge marks it acknowledged, by "You", and says so', /acknowledged/.test((await alertRow())[0]) && (await alertRow())[0].includes('You ·') && (await toast()) === 'Alert acknowledged' && (await device()).alerts[0].state === 'acknowledged')
  check('then it can only be resolved', same(await menuItems(), ['Resolve']))
  await rowMenu('.data-table tbody tr', 'Threshold breach', 'Resolve')
  const resolved = (await device()).alerts[0]
  check('Resolve resolves it, with a reason, and it can then do nothing more', resolved.state === 'resolved' && resolved.resolveReason === 'Manually resolved via console' && (await alertRow())[0].includes('Manually resolved via console') && (await menuItems()).length === 0 && (await toast()) === 'Alert resolved', resolved)
  await page.click('[data-json-toggle]')
  check('the JSON columns open to show their content', (await page.$$eval('.json-cell-pre:not(.hidden)', (els) => els.length)) === 1)

  // --------------------------------------------------------------- commands
  section('Commands')
  await fresh()
  await tab('commands')
  const history = () => page.$$eval('#commands-table-host tbody tr', (rows) => rows.map((r) => Array.from(r.children).map((c) => c.textContent.replace(/\s+/g, ' ').trim())))
  const hist0 = await history()
  check('the history starts with the two commands the device was given, both delivered', hist0.length === 2 && same(hist0.map((r) => r[0]).sort(), ['Ping', 'Restart']) && hist0.every((r) => r[1] === 'delivered' && r[2] === '200'), hist0)
  const types = await page.$$eval('#command-type-options option', (els) => els.map((el) => el.value))
  check('the command type offers the device\'s own commands', same(types, ['Ping', 'Restart', 'Request status report']), types)
  await page.click('.solid-action-button:has-text("Run")')
  check('Run with no command type does nothing', (await history()).length === 2)
  await page.fill('#commandType', 'Request status report')
  await page.fill('#commandBody', '{ not json')
  await page.click('.solid-action-button:has-text("Run")')
  check('a body that is not JSON is refused with a message', (await page.locator('#command-body-error').isVisible()) && (await page.textContent('#command-body-error')) === 'Command body must be valid JSON.' && (await history()).length === 2)
  await page.fill('#commandBody', '{"verbose": true}')
  await page.click('input[name="exec"][value="sync"]')
  await page.click('.solid-action-button:has-text("Run")')
  const afterSync = await history()
  check('a synchronous command is in the history at once, settled, with its body', afterSync.length === 3 && afterSync.some((r) => r[0] === 'Request status report' && /delivered|failed/.test(r[1]) && r[4].includes('"verbose": true')) && !(await page.locator('#command-body-error').isVisible()), afterSync)
  check('and the toast names it', (await toast()) === '"Request status report" command sent')
  await page.fill('#commandType', 'Restart')
  await page.click('input[name="exec"][value="async"]')
  await page.click('.solid-action-button:has-text("Run")')
  const afterAsync = await history()
  check('an asynchronous command starts as pending, with no status code', afterAsync.length === 4 && afterAsync.some((r) => r[0] === 'Restart' && r[1] === 'pending' && r[2] === '—' && r[3] === 'Pending'), afterAsync)
  await page.fill('#commands-search', 'status')
  check('the history can be searched by command type', (await history()).length === 1 && (await history())[0][0] === 'Request status report')
  await page.fill('#commands-search', '')
  await page.click('[data-sort-key="name"]')
  const asc = (await history()).map((r) => r[0])
  await page.click('[data-sort-key="name"]')
  const desc = (await history()).map((r) => r[0])
  check('clicking a column sorts by it, and again reverses it', same(asc, asc.slice().sort((a, b) => a.localeCompare(b))) && same(desc, asc.slice().reverse()), { asc, desc })

  section('A command that falls due while the page is closed')
  await page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem(STORAGE_KEY))
    const command = raw.devices.find((d) => d.id === 'd1').commands.find((c) => c.status === 'pending')
    if (command) command.dueAt = Date.now() - 5000
    localStorage.setItem(STORAGE_KEY, JSON.stringify(raw))
  })
  await open('device-detail.html#d1')
  await tab('commands')
  const settledHistory = await history()
  check('opening the device again settles it: no command is left pending', settledHistory.length === 4 && settledHistory.every((r) => r[1] !== 'pending'), settledHistory)

  // -------------------------------------------------------------- relations
  section('Relations')
  await fresh()
  await tab('relations')
  check('with none set, there are buttons to add a parent and children', (await page.locator('#add-parent-btn').count()) === 1 && (await page.locator('#add-child-btn').count()) === 1 && !(await page.locator('[data-relation-box]').count()))
  await page.click('#add-parent-btn')
  const parentOptions = await page.$$eval('[data-relation-select="parent"] option:not([disabled])', (els) => els.map((el) => el.value))
  check('the parent can be any other device', !parentOptions.includes('d1') && parentOptions.length === 12 && parentOptions.includes('d2'), parentOptions)
  await page.selectOption('[data-relation-select="parent"]', 'd2')
  check('choosing one sets it as the parent', (await toast()) === '"HVAC Compressor A" set as parent' && same((await device()).relations.map((r) => [r.type, r.relatedDeviceId]), [['parent', 'd2']]))
  check('the box then shows the chosen device', (await page.inputValue('[data-relation-select="parent"]')) === 'd2')
  await page.click('#add-child-btn')
  const childOptions = await page.$$eval('[data-relation-select="child-new"] option:not([disabled])', (els) => els.map((el) => el.value))
  check('a child can be any other device except the parent', !childOptions.includes('d1') && !childOptions.includes('d2') && childOptions.length === 11, childOptions)
  await page.selectOption('[data-relation-select="child-new"]', 'd4')
  check('choosing one adds it as a child', (await toast()) === '"Generator 12" added as child' && (await device()).relations.some((r) => r.type === 'child' && r.relatedDeviceId === 'd4'))
  await page.click('[data-remove-relation="parent"]')
  await page.waitForSelector('#confirm-dialog-confirm')
  await page.click('#confirm-dialog-confirm')
  check('removing the parent asks first, then removes it', !(await device()).relations.some((r) => r.type === 'parent') && (await device()).relations.length === 1)
  await page.click('[data-remove-relation^="child-"]')
  await page.waitForSelector('#confirm-dialog-confirm')
  check('removing a child names it', (await page.textContent('.confirm-dialog-message')).includes('Generator 12'))
  await page.click('#confirm-dialog-confirm')
  check('and removes it', (await device()).relations.length === 0)

  // ------------------------------------------------------------ data publish
  section('Data publish and data logs')
  await fresh()
  await tab('dataPublish')
  const code = () => page.textContent('.json-code-block:last-of-type')
  check('it starts with MQTT: its address, its topic and a mosquitto example', (await page.textContent('.publish-top-row')).includes('mqtt://mqtt.monitoring.pro') && (await code()).includes('mosquitto_pub') && (await page.locator('.topic-pub').count()) === 1)
  check('the example payload holds the device\'s metrics', (await page.textContent('.json-code-block')).includes('"speed"') && (await page.textContent('.json-code-block')).includes('"battery"'))
  await page.click('[data-code-tab="Python"]')
  check('another code tab changes the example', (await code()).includes('paho.mqtt.publish'))
  await page.click('[data-payload-mode="batched"]')
  check('a batched payload is a list', (await page.textContent('.json-code-block')).trim().startsWith('['))
  await page.click('[data-protocol="http"]')
  check('HTTP changes the address, the example and offers a token box and Send request', (await page.textContent('.publish-top-row')).includes('https://cloud.monitoring.pro/kpc') && (await code()).includes('curl -X POST') && (await page.locator('#device-token-input').count()) === 1 && (await page.locator('#send-request-btn').count()) === 1)
  await page.click('#send-sample-btn')
  check('Send data samples records a sample', (await toast()) === 'Sample data sent and recorded' && (await device()).logs.length === 2)
  await page.click('#send-request-btn')
  check('so does Send request', (await toast()) === 'Request sent and recorded' && (await device()).logs.length === 4)
  await tab('dataLogs')
  const logs = await page.$$eval('.data-table tbody tr', (rows) => rows.map((r) => r.textContent.replace(/\s+/g, ' ').trim()))
  check('Data logs lists an outbound and an inbound message for each', logs.length === 4 && logs.filter((r) => r.includes('INBOUND')).length === 2 && logs.filter((r) => r.includes('OUTBOUND')).length === 2, logs)
  await page.click('[data-json-toggle^="log-payload-"]')
  check('a payload opens to its JSON', (await page.$$eval('.json-cell-pre:not(.hidden)', (els) => els[0].textContent)).includes('"speed"'))

  // --------------------------------------------------------- custom widgets
  section('Custom widgets, and deleting the device')
  await fresh()
  await tab('widgets')
  await page.waitForSelector('.dashboard-canvas')
  check('the Custom widgets tab shows a dashboard of its own, with the widget button', (await page.locator('.dashboard-canvas').count()) === 1 && !(await page.evaluate(() => document.getElementById('widget-palette-fab').classList.contains('hidden'))))
  await tab('overview')
  check('the widget button is hidden on the other tabs', await page.evaluate(() => document.getElementById('widget-palette-fab').classList.contains('hidden')))
  await page.click('#device-actions-btn')
  check('Actions opens a menu with Delete device', (await page.textContent('#device-actions-dropdown')).includes('Delete device'))
  await page.click('#device-delete-btn')
  await page.waitForSelector('#confirm-dialog-confirm')
  check('Delete device asks first, naming it', (await page.textContent('.confirm-dialog-message')).includes('Forklift Unit 3'))
  await page.click('#confirm-dialog-cancel')
  check('Cancel keeps it', (await page.locator('.device-detail-title').count()) === 1 && Boolean(await device()))
  await page.click('#device-actions-btn')
  await page.click('#device-delete-btn')
  await page.waitForSelector('#confirm-dialog-confirm')
  await page.click('#confirm-dialog-confirm')
  await page.waitForURL(/devices\.html/)
  await page.waitForSelector('#devices-tbody')
  check('Delete goes back to the device list, and the device is gone', !(await device()) && !(await page.textContent('#devices-tbody')).includes('Forklift Unit 3'))

  await open('device-detail.html#d1')
  check('opening a device that is gone says so and links back to the list', (await page.textContent('.device-not-found')) === 'This device no longer exists.' && (await page.getAttribute('.device-detail-page a', 'href')) === 'devices.html')

  check('no JavaScript errors on the way', errors.length === 0, Array.from(new Set(errors)).slice(0, 5))
})
